config/routes.rb
Rails.application.routes.draw do
    root to: "catalogs#index"
    
    namespace :admin do
      get 'base/index'
      get '/add_publisher', to: 'publishers#new', as: 'add_publisher'
      
      resources :authors
      resources :books
      resources :publishers, except: [:new]
    end
    
    get '/signup', to: 'users#new', as: 'signup'
    get '/signin', to: 'sessions#new', as: 'signin'
    post '/signin', to: 'sessions#create'
    
    
    
  resources :books, only: [:show]
  resources :users, only: [:index, :show, :new, :create]
  resource :session
  resources :catalogs, only: [:index, :show] do
    collection do
      post :search, to: 'catalogs#search'
    end
  end
  
  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create]
  resources :orders, only: [:new, :create]
  
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :set_cart_if_session, except: [:search]
  def index
    @books = Book.paginate(:page => params[:page], :per_page => 3)
  end
    
  def show
    @book = Book.find params[:id]
    set_cart if session[:cart_id]
  end
    
  def search
    @books = Book.search_by_title(params[:search_word])
  end
    
  private
  def set_cart_if_session
      
  end
end

app/views/catalogs/index.html.erb
<section>
  <header>
    <% if @books.empty? %>
      <h3>No Books Entered</h3>
    <% else %>
      <h3 class="titles text-center">All Books</h3>
    <% end %>
  </header>
  
  <div id="paginate">
    <%= will_paginate @books, rederer: BootstrapPagination::Rails, class: "pull-left paginate" %>
  </div>
  
  <% @books.each do |book| %>
    <p class='book-title'>
      <%= link_to book.title, catalog_path(book) %><br>
      <span class='price-class'><%= number_to_currency(book.price) %></span>
    </p>
    <p class='book-image'><%= image_tag(book.book_cover_url(:thumb)) if book.book_cover? %></p>
    <div>
      <hr>
    </div>
  <% end %>
  <br>
</section>

app/views/catalogs/search.html.erb
<article>
  <div class="row">
    <% @books.each do |book| %>
      <label class="col-md-9"><%= link_to book.title, book %></label>
      <div class="col-md-4">
        <%= link_to image_tag(book.book_cover_url(:thumb)), book %>
      </div>
      <hr class="col-md-9">
    <% end %>
  </div>
</article>

app/views/catalogs/show.html.erb
<section>
  <div class='row'>
    <div class='col-md-12'>
      <header class='col-md-10'>
        <h3 class='titles text-center' id='book-show'><%= "#{@book.title}" %>'s Details</h3>
      </header>
      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>ISBN:</strong>
        </div>
        <div class='col-md-9'>
          <%= @book.isbn %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>Page count:</strong>
        </div>
        <div class='col-md-9'>
          <%= @book.page_count %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>Price:</strong>
        </div>
        <div class='col-md-9'>
          <%= number_to_currency(@book.price) %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>Description:</strong>
        </div>
        <div class='col-md-9'>
          <%= @book.description %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>Publisher:</strong>
        </div>
        <div class='col-md-9'>
          <%= @book.publisher.name %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>Published at:</strong>
        </div>
        <div class='col-md-9'>
          <%= @book.published_at %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class='col-md-10'>
        <div class='col-md-3'>
          <strong>Book cover:</strong>
        </div>
        <div class='col-md-9'>
          <%= image_tag(@book.book_cover_url) if @book.book_cover? %>
        </div>
      </div>
      <div class='col-md-10'>
        <hr>
      </div>

      <div class="col-md-10">
        <%= button_to "Add to cart", cart_items_path(book_id: @book.id), remote: true, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</section>